#ifndef TESTTYPES_H
#define TESTTYPES_H

enum ReqType { REGISTER_MESH, REQUEST_MESH, INFO_REQUEST, MESH_UPDATE, REQUEST_MESH_UPDATE};

enum EditType { ADD, DEL, EDIT };

enum PolyType { CUBE };

#endif